import { NextRequest, NextResponse } from 'next/server';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ claimId: string }> }
) {
  const { claimId } = await params;
  const body = await request.json().catch(() => ({}));
  const documentType = body.type || 'lba'; // 'lba' or 'evidence_pack'

  try {
    if (documentType === 'lba') {
      // Generate Letter Before Action
      const lba = generateDemoLBA(claimId);
      return NextResponse.json({
        claimId,
        type: 'lba',
        document: lba,
        generatedAt: new Date().toISOString(),
      });
    } else {
      // Generate Evidence Pack
      const pack = generateDemoEvidencePack(claimId);
      return NextResponse.json({
        claimId,
        type: 'evidence_pack',
        document: pack,
        generatedAt: new Date().toISOString(),
      });
    }
  } catch (error) {
    console.error('Generation error:', error);
    return NextResponse.json(
      { error: 'Document generation failed' },
      { status: 500 }
    );
  }
}

function generateDemoLBA(claimId: string): string {
  return `# LETTER BEFORE ACTION

**WITHOUT PREJUDICE SAVE AS TO COSTS**

**SENT BY EMAIL AND FIRST CLASS POST**

Date: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}

**PRIVATE AND CONFIDENTIAL**

Dear Sir/Madam,

## RE: CLAIM FOR BREACH OF CONTRACT

We act on behalf of our client in relation to the above matter.

### Background

Our client entered into a contractual agreement with you/your company. The terms of this agreement were clear and unambiguous.

### The Breach

Despite the clear terms of the agreement, you have failed to honour your contractual obligations. Specifically:

1. Failure to deliver the agreed services/goods within the specified timeframe
2. Failure to meet the quality standards specified in the agreement
3. Failure to communicate regarding the ongoing issues

### Evidence

Our client holds substantial evidence supporting this claim, including but not limited to:
- The original signed contract/agreement
- Email correspondence demonstrating the breach
- WhatsApp communications confirming commitments made
- Financial records evidencing loss suffered

### Legal Position

Our client has a strong claim for breach of contract. The elements of the claim are clearly established:
- A valid and binding contract existed between the parties
- You breached the material terms of that contract
- Our client has suffered quantifiable loss as a direct result

### Remedies Sought

Our client seeks the following remedies:
1. **Damages**: Compensation for all losses suffered as a result of the breach
2. **Interest**: Statutory interest on all sums due
3. **Costs**: All reasonable legal costs incurred in pursuing this claim

### What You Need To Do

We require that you:

1. **Within 14 days of this letter**, provide a full and substantive response to the matters raised herein
2. Confirm your proposals for resolving this matter without the need for court proceedings

### Consequences of Non-Response

Should we not receive a satisfactory response within 14 days, our client reserves the right to:
- Issue court proceedings without further notice
- Seek a costs order against you
- Apply for interest on all sums claimed

We draw your attention to the Pre-Action Protocol for Debt Claims / Professional Negligence / General Claims and the court's expectation that parties make genuine attempts to resolve disputes before litigation.

**This letter constitutes formal notification of our client's claim and the commencement of the pre-action protocol.**

Yours faithfully,

**Atticus**
*Legal Document Preparation Service*

---
*Claim Reference: ${claimId}*
*Generated by Atticus - This document should be reviewed by a qualified legal professional before sending.*`;
}

function generateDemoEvidencePack(claimId: string): string {
  return `# EVIDENCE PACK & CASE BUNDLE

**Claim Reference:** ${claimId}
**Generated:** ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}

---

## TABLE OF CONTENTS

1. Case Summary
2. Timeline of Events
3. Evidence Index
4. Legal Analysis
5. Forensic Findings
6. Strength Assessment
7. Available Remedies

---

## 1. CASE SUMMARY

[This section will contain the AI-compiled summary of the claim based on the intake conversation and evidence analysis.]

## 2. TIMELINE OF EVENTS

[Interactive timeline data will be embedded here, showing all key events in chronological order with references to supporting evidence.]

## 3. EVIDENCE INDEX

| # | Document | Type | Date | Relevance | Tags |
|---|----------|------|------|-----------|------|
| 1 | Contract.pdf | Contract | - | High | Contract Terms, Agreement |
| 2 | Email Thread | Correspondence | - | High | Breach, Communication |
| 3 | WhatsApp Export | Messages | - | Medium | Admission, Timeline |

## 4. LEGAL ANALYSIS

### Causes of Action
[Detailed analysis of each cause of action with element-by-element assessment]

### Anticipated Defenses
[Analysis of likely defenses with counter-arguments]

### Relevant Case Law
[Citations to relevant judgments and their implications]

## 5. FORENSIC FINDINGS

### Document Integrity: STRONG
[Forensic analysis results for each piece of evidence]

## 6. STRENGTH ASSESSMENT

**Overall Claim Strength: 78/100 (STRONG)**

| Factor | Score |
|--------|-------|
| Facts Strength | 82/100 |
| Evidence Strength | 75/100 |
| Legal Basis | 80/100 |
| Remedy Likelihood | 74/100 |

## 7. AVAILABLE REMEDIES

| Remedy | Estimated Value | Likelihood |
|--------|----------------|------------|
| Damages | £50,000 - £75,000 | High |
| Interest | £3,000 - £5,000 | High |
| Costs | £10,000 - £15,000 | Medium |

---

*Generated by Atticus*
*This document should be reviewed by a qualified legal professional.*`;
}
